---
title: "TidyTemplate"
date: 2021-04-07
output: html_output
---

# TidyTuesday



```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(scales)
theme_set(theme_light())
```

# Load the weekly Data

Dowload the weekly data and make available in the `tt` object.

```{r Load}

tt <- tt_load("2021-04-06")

```


# Readme

Take a look at the readme for the weekly data to get insight on the dataset.
This includes a data dictionary, source, and a link to an article on the data.

```{r Readme, eval = interactive()}

tt

```



```{r}
forest <- tt$forest %>% 
  rename(country = entity)

forest %>% 
  count(country) %>% view


forest %>%
  filter(year == 2015,
         nchar(code)==3) %>% 
  arrange(net_forest_conversion) %>% 
  slice_max(abs(net_forest_conversion), n = 15) %>% 
  mutate(country = fct_reorder(country, net_forest_conversion)) %>% 
  ggplot(aes(net_forest_conversion, country, fill = net_forest_conversion>0)) +
  geom_col() +
  scale_x_continuous(labels = comma) +
  theme(legend.position = "none") +
  labs(x = "Net forest conversion",
       y = "")
  

library(forcats)

# how to use lump
forest %>% 
  mutate( country = fct_lump(country, 4, w = abs(net_forest_conversion))) %>%
  summary()
            


```
